services:
  mongodb:
    image: mongo:5.0.24-focal
    restart: unless-stopped
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./repos/lishogi-db-scripts:/lishogi-db-scripts

  redis:
    image: redis:7.2.4-alpine3.19
    restart: unless-stopped
    hostname: redis
    ports:
      - 6379:6379

  lila_ws:
    build:
      context: docker
      dockerfile: lila-ws.Dockerfile
    restart: unless-stopped
    ports:
      - 9664:9664
    volumes:
      - ./repos/lila-ws:/lila-ws
      - ./conf/lila-ws.conf:/lila-ws.conf

  shoginet:
    build:
      dockerfile: docker/shoginet.Dockerfile
    restart: unless-stopped
    extra_hosts:
      # https://github.com/docker/compose/issues/2915
      # Prefer a different name rather than overriding `host.docker.internal', it causes confusion.
      - 'lila:${DOCKER_HOST_IP}'
