services:
  mongodb:
    image: mongo:5.0.24-focal
    restart: unless-stopped
    hostname: mongodb
    ports:
      - 27017:27017

  redis:
    image: redis:7.2.4-alpine3.19
    restart: unless-stopped
    hostname: redis
    ports:
      - 6379:6379

  lila_ws:
    build:
      context: docker
      dockerfile: lila-ws.Dockerfile
    restart: unless-stopped
    ports:
      - 9664:9664
    volumes:
      - ./repos/lila-ws:/lila-ws
      - ./conf/lila-ws.conf:/lila-ws.conf
