# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      - nix flake check
  fmt:
    cmds:
      - dprint fmt
      - nixpkgs-fmt ./*.nix
      - shfmt --write ./*.bash
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      - nixpkgs-fmt --check ./*.nix
      - shellcheck ./*.bash
  deps:
    cmds:
      - nix --version
      - nil --version
      - task --version
      - dprint --version
      - typos --version
      - shellcheck --version
      - shfmt --version
      - docker --version
      - sbt --version
      - node --version
      - yarn --version
