# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      - nix flake check
  fmt:
    cmds:
      - dprint fmt
      - nixpkgs-fmt ./*.nix
      - shfmt --write ./scripts/*.bash
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      - nixpkgs-fmt --check ./*.nix
      - shellcheck ./scripts/*.bash
  setup:
    cmds:
      - ./scripts/setup.bash
  pin:
    cmds:
      - ./scripts/pin_repos.bash
  prepare_db:
    cmds:
      - docker compose exec mongodb bash -c 'mongosh lishogi < /lishogi-db-scripts/utils/indexes.js'
  deps:
    cmds:
      - nix --version
      - nil --version
      - task --version
      - dprint --version
      - typos --version
      - shellcheck --version
      - shfmt --version
